#!/bin/bash

ARGS=$(getopt -o x:p:vl -- "$@");
eval set -- "$ARGS";

EXEC=cutes
VERBOSE=false
USE_CUTES_PATH=
TAG="<T>"

function trace {
    if $VERBOSE; then
        echo $TAG $@
    fi
}

while true; do
    case "$1" in
        -x)
            EXEC=$2
            shift 2;
            ;;
        -p)
            USE_CUTES_PATH=$2
            shift 2;
            ;;
        -v)
            echo "$TAG Verbose"
            VERBOSE=true
            shift 1;
            ;;
        -l)
            EXEC=../cutes/cutes
            USE_CUTES_PATH=../lib:./
            shift 1;
            ;;
        --)
            shift;
            ;;
        *)
            break;
            ;;
    esac
done

EXEC=`which $EXEC`
export LD_LIBRARY_PATH="`dirname $EXEC`:$LD_LIBRARY_PATH"
trace "Executable is $EXEC"
trace "LD_LIBRARY_PATH $LD_LIBRARY_PATH"

if [ "x$USE_CUTES_PATH" != "x" ]; then
    export CUTES_LIBRARY_PATH=$USE_CUTES_PATH
    trace "Using CUTES_LIBRARY_PATH: $CUTES_LIBRARY_PATH"
fi

COUNT=0
FAILED_COUNT=0
FAILED=""
function check_res {
    if [ $# -ne 3 ]; then
        echo "$TAG Unexpected params: $@"
    fi
    ((COUNT++))
    cmd=$1
    expected=$2
    test=$3
    trace "Executing TEST $cmd"
    if $VERBOSE; then
        data=`$cmd`
        res=$?
        echo "$data"
    else
        `$cmd &>/dev/null`
        res=$?
    fi
    if [ $res -ne $expected ]; then
        echo "$TAG TEST IS FAILED: $test. Got $res instead of $expected"
        ((FAILED_COUNT++))
        FAILED+=" \"$test\""
        #exit $res
    fi
}

EXIT_FAILURE=1

# check exiting with error if non-existing files are supplied
cmd="cutes non_existing.qml"
check_res "$cmd" $EXIT_FAILURE "Loading non-existing qml"
cmd="cutes non_existing.js"
check_res "$cmd" $EXIT_FAILURE "Loading non-existing js"
cmd="cutes -cli non_existing.qml"
check_res "$cmd" $EXIT_FAILURE "Loading non-existing qml in cli mode"

cmd="cutes empty.js"
check_res "$cmd" 0 "Loading empty js"

cmd="cutes bad.js"
check_res "$cmd" $EXIT_FAILURE "Loading bad js"

cmd="cutes load_actor_bad.js bad.js"
check_res "$cmd" $EXIT_FAILURE "load_actor_bad"

cmd="cutes globals.js"
check_res "$cmd" 0 "globals"

cmd="cutes load_actor_globals.js"
check_res "$cmd" 0 "load_actor_globals"

cmd="cutes throws.js"
check_res "$cmd" $EXIT_FAILURE "throws"

cmd="cutes load_actor_bad.js throws.js"
check_res "$cmd" $EXIT_FAILURE "load_actor_throws"

echo "$TAG RESULTS: (OK $COUNT) (FAILED $FAILED_COUNT)"
if [ $FAILED_COUNT -ne 0 ]; then
    echo "$TAG FAILED: ($FAILED)"
fi
