* cutes - QtScript "interpreter" and environment

cutes is used to execute QtScript javascript applications and also Qt
applications with declarative UI using QtScript environment provided
by cutes and background tasks using this environment. See doc/

It is recommended to use cutes with extensions generated by
qtscriptgenerator, giving javascript applications access to almost all
Qt functionality

** Examples

   To use examples one should install cutes.js libraries
