.TH "cutes" "1" "Jolla Ltd." "Feb 11, 2013"
.SH "NAME"
.PP
cutes allows to run JavaScript and QML files with QtScript support
.SH "SYNOPSIS"
.PP
\fBcutes\fP [-h] \fIscript\d\s-2file\s+2\u\fP [script arguments]
.SH "DESCRIPTION"
.PP
QtScript is the Qt library JavaScript engine. cutes command
provides the way to run JavaScript files as shell scripts or to load QML
UI with QtScript support.
.SH "COMMAND LINE OPTIONS"
.TP
\fB\fB-h\fP\fP
show usage
.TP
\fB\fBscript\d\s-2file\s+2\u\fP\fP
name of the javascript or qml file to be executed,
files with .qml extension will be considered as 
QML UI files, other - as JS files
.TP
\fB\fB[script arguments]\fP\fP
arguments to be passed to javascript in
the \fBqtscript.args\fP variable
.SH "ENVIRONMENT"
.TP
\fB\fBQTSCRIPT\_LIBRARY\_PATH\fP\fP
contains colon-separated list of
paths to directories containing QtScript extensions and
JavaScript modules, available for importing. Because this paths
are just library paths, extensions themselves (shared objects)
should reside in subdirectories ./script/. JavaScript modules
should reside in ./. By default qtscript is trying to add
/usr/lib{,32,64}/qt4/plugins directories.
.SH "JAVASCRIPT CONTEXT"
.PP
qtscript provides several objects/functions, available in executed
scripts.

.TP
\fB\fBqtscript.os\fP\fP
OS "name": can be any of ["linux", "macos",
"win32", "unknown"]
.TP
\fB\fBqtscript.env\fP\fP
environment variables
.TP
\fB\fBqtscript.path\fP\fP
Application library paths
.TP
\fB\fBqtscript.include\fP\fP
function to execute javascript file by file
name. File name can be absolute or relative to the directory
where running script resides or to any directory in the library
path. Result of execution is returned
.TP
\fB\fBqtscript.extend\fP\fP
instructs engine to import QtScript extension
.TP
\fB\fBqtscript.module.args\fP\fP
list of command line arguments
.TP
\fB\fBqtscript.module.filename\fP\fP
currently executed script file name
(e.g. in \fBqtscript.include\fP it will be included script path name)
.TP
\fB\fBqtscript.module.cwd\fP\fP
current working directory or directory
where currently executed/evaluated script is located
.TP
\fB\fBmodule\fP\fP
current file module object, resembling e.g. node.js
module object
.TP
\fB\fBrequire\fP\fP
synonym for qtscript.include, compatible with other
module systems, returns symbols exported by module
.TP
\fB\fBexports\fP\fP
object to be used to hold exported symbols, it is just
reference to the current module.exports. QtScript
engine resolves it only in file scope but does not do
it inside internal scopes (functions etc.)
.SH "AUTHOR"
.PP
Denis Zalevskiy <denis.zalevskiy@jollamobile.com>
.SH "LICENSING"
.PP
cutes is distributed under terms and conditions of the LGPLv2
license.
