#+TITLE:qtscript
#+MAN_CLASS_OPTIONS: :section-id 1 :company "Jolla Ltd." :date "Jan 30, 2013"
* NAME

  qtscript allows to run JavaScript and QML files with QtScript support

* SYNOPSIS

  *qtscript* [-h] /script_file/ [script arguments]

* DESCRIPTION

QtScript is the Qt library JavaScript engine. qtscript command
provides the way to run JavaScript files as shell scripts or to load QML
UI with QtScript support.

* COMMAND LINE OPTIONS

  - *-h* :: show usage
  - *script_file* :: name of the javascript or qml file to be executed,
                     files with .qml extension will be considered as 
                     QML UI files, other - as JS files
  - *[script arguments]* :: arguments to be passed to javascript in
       the *qtscript.args* variable

* ENVIRONMENT

  - *QTSCRIPT\_LIBRARY\_PATH* :: contains colon-separated list of
       paths to directories containing QtScript extensions and
       JavaScript modules, available for importing. Because this paths
       are just library paths, extensions themselves (shared objects)
       should reside in subdirectories ./script/. JavaScript modules
       should reside in ./. By default qtscript is trying to add
       /usr/lib{,32,64}/qt4/plugins directories.

* JAVASCRIPT CONTEXT

  qtscript provides several objects/functions, available in executed
  scripts. All this variables are members of the global *qtscript*
  object.

- *qtscript.system.os* :: OS "name": can be any of ["linux", "macos",
     "win32", "unknown"]
- *qtscript.system.env* :: environment variables
- *qtscript.system.path* :: Application library paths
- *qtscript.load* :: function to load javascript file located in the
     directory where running script resides or in the library path
- *qtscript.use* :: instructs engine to import QtScript extension
- *qtscript.script.args* :: list of command line arguments
- *qtscript.script.filename* :: currently executed script file name
     (e.g. in *qtscript.eval* it will be evaluated script path name)
- *qtscript.script.cwd* :: current working directory or directory where
                    executed/evaluated script is located

* AUTHOR
  Denis Zalevskiy <denis.zalevskiy@jollamobile.com>

* LICENSING
  qtscript is distributed under terms and conditions of the LGPLv2
  license.
